spring:
  profiles:
    active: dev
  application:
    name: user-center
    # DataSource Config mysql数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yellowapi
    username: root
    password: 123456
    # Session失效时间（分钟）
  session:
    timeout: 10m
    # 配置redis存储session
    #store-type: redis
    # knife4j
  mvc:
    pathmatch:
      # 配置策略
      matching-strategy: ant_path_matcher
  # redis数据库配置
  redis:
    port: 6379
    host: localhost
    database: 1
    # Session失效时间（分钟）
  #Es配置
  elasticsearch:
    uris: http://localhost:9200
    username: root
    password: 123456
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain:
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # mybatis日志显示
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
# 这段配置是测试的
yellowapi:
  client:
    access-key: chl
    secret-key: 123456
# 应用程序名称
dubbo:
  application:
    name: spring-dubbo-provider
  # Dubbo 通讯协议
  # Dubbo服务提供的端口， 配置为-1，代表为随机端口
  protocol:
    name: dubbo
    port: -1
  ## Dubbo 注册器配置信息
  registry:
    id: nacos-registry
    address: nacos://localhost:8848

# 异步线程配置
# 配置核心线程数
async:
  executor:
    thread:
      core_pool_size: 10
      # 配置最大线程数
      max_pool_size: 30
      # 配置队列大小
      queue_capacity: 99988
      # 配置线程池中的线程的名称前缀
      name:
        prefix: async-importDB-
